title: App Academy Prep-Work
description: Prepare for App Academy with this material
baseurl: "/prep-work"

aa-url: http://www.appacademy.io/#p-home
contact-desc: "Please contact us with any questions or concerns:"
contact-email: contact@appacademy.io

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
